[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tom_swe"
version = "0.1.0"
description = "Theory of Mind for Software Engineering"
readme = "README.md"
authors = [
    {name = "OpenHands", email = "openhands@all-hands.dev"}
]
license = {text = "MIT"}
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov>=2.12",
]

[tool.pytest.ini_options]
testpaths = ["tom_swe/tests"]